---
collections:

  # Install a collection from Ansible Automation Hub.
  - name: ansible.tower
    version: '3.7.3'
    source: https://cloud.redhat.com/api/automation-hub/

#  - name: redhat.satellite
#  - name: ansible.netcommon
#  - geerlingguy.php_roles
#  - ansible.tower
#  - name: community.vmware
#    version: '1.9.1-dev8'
#  - name: community.general
#  - name: ansible.netcommon

