---
collections:
  - name: infra.aap_configuration
  - name: ansible.controller
  - name: ansible.hub
  - name: ansible.platform
  - name: cloud.common
  - name: kubernetes.core
  - name: infra.aap_utilities
