---
- name: image pull
  hosts: localhost
  connection: local
  tasks:
    - name: Login to default registry and create ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        username: 'admin'
        password: 'redhat'
        registry: 'aeladawy-aap23-pah.example.com'
        tlsverify: false

#    - name: Image pull using command
#      command: "podman pull aeladawy-aap23-pah.example.com/ansible-automation-platform-22/ee-29-rhel8 --tls-verify=false"
    - name: pull the containers
      containers.podman.podman_image:
        name: aeladawy-aap23-pah.example.com/ansible-automation-platform-22/ee-29-rhel8
