---
- name: image pull
#  hosts: aeladawy-aap23-controller.example.com
  hosts: localhost
  connection: local
  tasks:
#    - name: Edit /etc/subuid and /etc/subgid
#      ansible.builtin.lineinfile:
#        path: "{{ item }}"
#        line: root:100000:65536
#      loop:
#        - /etc/subuid
#        - /etc/subgid

 #   - name: Ignore storage chown_errors
 #     ansible.builtin.lineinfile:
 #       path: /etc/containers/storage.conf
 #       regexp: '#ignore_chown_errors = "false"'
 #       line: ignore_chown_errors = "true"

 #   - command: cat /etc/subuid /etc/subgid
 #   - command: grep ignore_chown_errors /etc/containers/storage.conf
    
    - name: Login to default registry and create ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        username: 'admin'
        password: 'redhat'
        registry: 'aeladawy-aap23-pah.example.com'
        tlsverify: false

    - name: Edit /etc/subuid and /etc/subgid
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        line: root:100000:65536
      loop:
        - /etc/subuid
        - /etc/subgid

    - name: Ignore storage chown_errors
      ansible.builtin.lineinfile:
        path: /etc/containers/storage.conf
        regexp: '#ignore_chown_errors = "false"'
        line: ignore_chown_errors = "true"
 
    - name: Image pull using command
      command: "podman pull aeladawy-aap23-pah.example.com/ansible-automation-platform-22/ee-29-rhel8 --tls-verify=false"
#    - name: pull the containers
#      containers.podman.podman_image:
#        name: aeladawy-aap23-pah.example.com/ansible-automation-platform-22/ee-29-rhel8
#        validate_certs: false
