- name: fetch files
  hosts: all
  gather_facts: false
  tasks:
    - name: get list of the result files
      find:
        path: /tmp/unix_inv
        patterns: '*_unix_inv.csv'
      register: file2fetch
    - name: fetch files to controller
      fetch:
        #flat: yes
        src: "{{ item.path }}"
        dest: "/tmp/unix_inv/"
      with_items: "{{ file2fetch.files }}"
