---
- name: test cifs mounts
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cifs_user: "sambauser"
    cifs_pass: "redhat"
    
  tasks:

#    - name: Check CIFS utils
#      ansible.builtin.command: microdnf install samba-client cifs-utils 

    - name: create mount directory
      ansible.builtin.file:
        path: /mnt/test
        state: directory
        mode: '777'

    - name: mount cifs share
      ansible.posix.mount:
        src: //192.168.100.23/Secure
        path: /mnt/test
        opts: "rw,username={{ cifs_user }},password={{ cifs_pass }}"
        fstype: cifs
        state: mounted
