---
- name: test cifs mounts
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    cifs_user: "sambauser"
    cifs_pass: "redhat"
  tasks:

  #  - name: Check CIFS utils
  #    ansible.builtin.package:
  #      name: cifs-utils
  #      state: present

    - name: create mount directory
      ansible.builtin.file:
        path: /mnt/test
        state: directory

    - name: mount cifs share
      ansible.posix.mount:
        src: //192.168.100.23/Secure
        path: /mnt/test
        opts: "rw,username={{ cifs_user }},password={{ cifs_pass }}"
        fstype: cifs
        state: mounted
