---
- name: ZIA Fetching
  gather_facts: no
  hosts: localhost
  vars:
    zia_cloud:
      username: "username_username"
      password: "password_password"
      api_key: "sdsdsdsdsdsdsdsd"
      cloud: "zscaler"

  tasks:
    - name: Fetching locations from Zscaler ZIA
      zscaler.ziacloud.zia_location_management_info:
        provider: "{{ zia_cloud }}"
      register: zia_locations

