---
- name: export aap job templates
  hosts: localhost
  connection: local

  tasks:
  - name: export the templates
    ansible.controller.export:
      controller_host: https://aeladawy-aap24-controller.example.com
      controller_username: "admin"
      controller_password: "redhat"
      validate_certs: false
      projects: "My github"
      inventory: ['aap inventory', 'lab inventory']
      job_templates: ['aap backup', 'os update']
    register: templates_export_output


  - name: import the job_templates
    ansible.controller.import:
      controller_host: https://10.1.230.80
      controller_username: "admin"
      controller_password: "redhat"
      validate_certs: false
      assets: "{{ templates_export_output.assets }}"
