---
- name: export aap job templates
  hosts: localhost
  connection: local

  tasks:
  - name: export the templates
    ansible.controller.export:
      controller_host: https://aeladawy-aap24-controller.example.com
      controller_username: "admin"
      controller_password: "redhat"
      validate_certs: false
      job_templates: ['collect facts', 'create aap credential']
