---
- name: collect facts
  gather_facts: false
  hosts: all
  #connection: local
  tasks:   
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: show version
      register: list_output
      
    - name: copy the list
      copy:
        content: "{{ list_output.stdout }}"
        dest: "/tmp/backup/config_backup-{{ date }}"
        #remote_src: true
      delegate_to: aeladawy-aap24-controller.example.com
