---
- name: collect facts
  gather_facts: false
  hosts: aeladawy-rhel9-client.example.com
  tasks:
    - name: list /tmp
      copy:
        remote_src: /tmp/aeladawy-rhel9-client.example.com
        dest: /tmp/backup/aeladawy-rhel9-client.example.com
      delegate_to: aeladawy-aap24-controller.example.com
