---
- name: collect facts
  gather_facts: false
  hosts: aeladawy-rhel9-client.example.com
  tasks:
    - name: list /tmp
      command: ls -l /tmp
      register: list_output
      
    - name: copy the list
      copy:
        content: "{{ list_output.stdout }}"
        dest: /tmp/backup/files_list.txt
        #remote_src: true
      delegate_to: aeladawy-aap24-controller.example.com
