---
- name: cat /etc/krb5.conf file
  gather_facts: false
  hosts: localhost
  connection: local
  tasks:
    - name: task1
      ansible.builtin.command: cat /etc/krb5.conf
    - name: task2
      ansible.builtin.command: ls -l /etc/krb5.conf
    - name: task3
      ansible.builtin.command: whoami
