---
- name: copy file to smb share playbook
  hosts: aeladawy-rhel9-client.example.com
  #connection: local
  gather_facts: false
  tasks:
    - name: copy file to smb share
      ansible.builtin.copy:
        mode: '0644'
        src: /mnt/file_to_copy.txt
        dest: /tmp
        remote_src: yes
#    - name: create empty file
#      file:
#        path: /share/touch_test2
#        state: touch
