---
- name: copy file to smb share playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: copy file to smb share
      ansible.builtin.copy:
        mode: '0644'
        src: /tmp/share1/inventory
        dest: /mnt/share1/
