---
- name: copy file to smb share playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: copy file to smb share
      file:
        path: "/share/touch_test2
        state: touch
#      ansible.builtin.copy:
#        mode: '0644'
#        src: /tmp/share1/inventory
#        dest: /mnt/share1/
