---
- name: Configuration d'un credential dans AAP
  hosts: localhost
  connection: local

  tasks:
  - name: Créer ou mettre à jour un credential dans AAP
    ansible.controller.credential:
      controller_host: https://localhost
      controller_username: "admin"
      controller_password: "redhat"
      validate_certs: false
      name: "Credential SSH pour Test"
      credential_type: Machine
      organization: Default   
      inputs:
        username: admin        
        password: password    
