---
- name: Configure credentials
  hosts: localhost
  connection: local

  tasks:
  - name: Create AAP credential
    infra.controller_configuration.credentials:
      name: "Credential SSH Test"
      description: "Credential used for SSH login in tests"
      credential_type: Machine
      organization: Default
      inputs:
        username: admin        
        password: password      
