---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  tasks:
  - name: Créer ou mettre à jour un credential dans AAP
    ansible.controller.credential:
      controller_host: https://aeladawy-aap24-controller.example.com
      controller_username: "admin"
      controller_password: "redhat"
      validate_certs: false
      name: localuser
      credential_type: Machine
      organization: Default   
      inputs:
        username: admin        
        password: password    
