---
- name: "Gateway Configuration"
  hosts: localhost
  connection: local
  vars:
    aap_hostname: "https://aeladawy-aap25-gateway.example.com"
    aap_validate_certs: no
    aap_username: admin
    aap_password: redhat
    
  collections:
    - infra.aap_configuration

  pre_tasks:
  - name: "pre_tasks: Include all secrets from vault and data to set"
    include_vars:
      file: "data/aap_user_accounts.yml"

  roles:
    - infra.aap_configuration.gateway_users
