---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  # Define following vars here, or in controller_configs/controller_auth.yml
  # controller_hostname: ansible-controller-web-svc-test-project.example.com
  # controller_username: admin
  # controller_password: changeme
  vars:
    controller_credentials:
      - name: localuser
        description: Machine Credential example with become_method input
        credential_type: Machine
        inputs:
          username: localuser
          password: password
          become_method: sudo
  roles:
    - {role: infra.controller_configuration.credentials, when: controller_credentials is defined}
