---
- name: Configuration d'un credential dans AAP
  hosts: localhost
  connection: local

  tasks:
  - name: Créer ou mettre à jour un credential dans AAP
    ansible.controller.credential:
      name: "Credential SSH pour Test"
      description: "Credential utilisé pour la connexion SSH dans les tests"
      credential_type: Machine
      organization: Default    
      inputs:
        username: admin        
        password: password    
