- name: debug facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: debug ansible_distribution_major_version
      debug:
        msg: "{{ ansible_distribution_major_version }}"
      when: ansible_distribution_major_version == '9'

    - name: debug ansible_distribution
      debug:
        msg: "{{ ansible_distribution }}"
      when: ansible_distribution == 'RedHat'
