- name: debug facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: debug ansible_distribution_major_version
      debug:
        msg: "{{ ansible_distribution_major_version }}"

    - name: debug ansible_distribution
      debug:
        msg: "{{ ansible_distribution }}"
