---
- name: image pull
  hosts: localhost
  connection: local
  tasks:
    - name: Login to default registry and create ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        username: 'admin'
        password: 'redhat'
        registry: 'aeladawy-aap24-pah.example.com'
        tlsverify: false

    - name: Image pull using command
      command: "podman pull aeladawy-aap24-pah.example.com/de-minimal-rhel8 --tls-verify=false"
