---
- name: satellite operations
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Find repository set by label"
      redhat.satellite.repository_set_info:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite }}"
        organization: "dorganization"
        search: "label=rhel-8-for-x86_64-appstream-rpms"
      register: output

    - name: debug
      debug:
        var: output
