---
- name: test handlers
  hosts: all
  gather_facts: false
  tasks:
    - name: change index.html content
      lineinfile:
        path: /var/www/html/index.html
        line: "LogLevel debug"
        state: present
        backup: yes
      become: yes
      changed_when: True
      notify: Restart httpd
  handlers:
    - name: "Restart httpd daemon"
      ansible.builtin.systemd:
        name: "httpd.service"
        state: restarted
        daemon-reload: true
        enabled: true
      listen: Restart httpd
      become_user: root

    - name: "Wait for httpd to start"
      ansible.builtin.uri:
        url: "https://aeladawy-rhel9-client.example.com"
        validate_certs: false
      register: httpd_status
      until: httpd_status.status == 200
      retries: 5
      delay: 5
      listen: Restart httpd
      check_mode: false
