---
- name: test handlers
  hosts: all
  gather_facts: false
  tasks:
    - name: changed_when true
      ansible.builtin.debug:
        msg: "changed_when: true"
      changed_when: true
      notify: Restart httpd
      
    - name: changed_when true number 2
      ansible.builtin.debug:
        msg: "changed_when: true"
      changed_when: true
      notify: Restart httpd
      
    - name: changed_when false
      ansible.builtin.debug:
        msg: "changed_when: false"
      changed_when: false
      notify: Restart httpd
      
  handlers:
    - name: "Restart httpd daemon"
      ansible.builtin.systemd:
        name: "httpd.service"
        state: restarted
        daemon-reload: true
        enabled: true
      listen: Restart httpd
      become_user: root
