- name: Hello World Sample
  hosts: all
  gather_facts: yes
  environment:
    ANSIBLE_CALLBACK_PLUGINS: 
      - /runner/project/plugins/callback/
#    ANSIBLE_CALLBACKS_ENABLED: 
#      - ansible.posix.timer
#      - ansible.posix.profile_tasks
  
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ hello_message }}"
