- name: Hello World Sample
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ hello_message }}"
      environment:
        ANSIBLE_CALLBACKS_ENABLED: ansible.posix.profile_tasks,ansible.posix.timer
