- name: Install and enable Apache
  hosts: all
  gather_facts: false
  tasks:
    - name: httpd package is present
      yum:
        name: 
          - httpd
          - firewalld
        state: present
        
    - name: firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits access to httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
        
    - name: httpd service is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
