- name: Install and enable Apache
  hosts: all
  gather_facts: false
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
        
    - name: httpd service is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
