- name: Install and enable Apache
  hosts: all
  vars:
    apache_package: httpd
    apache_service: httpd
    apache_firewall_http_service: http
    firewall_package: firewalld
    firewall_service: firewalld
    
  gather_facts: false
  tasks:
    - name: httpd package is present
      yum:
        name: 
          - "{{ apache_package }}"
          - "{{ firewall_package }}"
        state: present
        
    - name: firewalld enabled and running
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: firewalld permits access to httpd service
      firewalld:
        service: "{{ apache_firewall_http_service }}"
        permanent: true
        state: enabled
        immediate: yes
        
    - name: httpd service is started and enabled
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
