---
- name: new Machine setup
  hosts: all
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ new_machine_hostname }}"
      notify:
        - reboot the machine

    - name: register the machine
      ansible.builtin.command: subscription-manager register --org=1979710 --activationkey=aeladawy-tower-ak --force
      when: ansible_distribution == "RedHat"    
  
    - name: Set authorized key
      ansible.posix.authorized_key:
        user: root
        key: "{{ public_key }}"  
        state: present
        
    - name: Install packages
      ansible.builtin.yum:
        name:
          - vim
          - mlocate
          - net-tools
          - chrony
      
    - name: start and enable chronyd service
      ansible.builtin.systemd_service:
        name: chronyd
        state: started
        enabled: true

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
      notify:
        - reboot the machine

  handlers:
    - name: reboot the machine
      ansible.builtin.reboot:
