- hosts: localhost
  connection: local
  tasks:
  - name: Send an email
    mail:
      to: "{{ dest_email }}"
      username: "{{ sender_email}}"
      password: "{{ email_password }}"
      host: smtp.gmail.com
      port: 587
      subject: This is the subject
      body: This is the email body
