- hosts: localhost
  connection: local
  tasks:
  - name: Send an email
    mail:
      to: test@test.com
      host: smtp.gmail.com
      port: 587
      subject: This is the subject
      body: This is the email body
