---
- name: Copy file to cifs share
  hosts: all  
  tasks:
    - name: Copy file to send
      ansible.builtin.copy:
        mode: '0644'
        src: /home/toexcel/test3.xlsx
        dest: /sharewin
        remote_src: yes
