---
- name: collect facts
  hosts: all
  gather_facts: false
  tasks:
    - name: update packages
      yum:
        name: '*'
        state: latest
        security: no
        exclude: "{{ exclude_rpm }}"
        update_cache: yes
