---
- name: collect facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Synchronization of src on the control machine to dest on the remote hosts
      ansible.posix.synchronize:
        src: /var/lib/awx/work/
        dest: /tmp/work/
        #rsync_path: /usr/bin/rsync
        mode: push
