---
- name: Set all the satellite content for SOE
  gather_facts: true
  hosts: all
  vars:
    satellite_organization: '{{ organization_name }}'
    satellite_server_url: 'https://{{ inventory_hostname }}'
    satellite_username: "admin"
    satellite_password: '{{ satellite_password }}'
    satellite_products:
      - name: Red Hat Enterprise Linux for x86_64
        repository_sets:
        - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
          arch: noarch
          releasever: 8.6


  tasks:

    - {import_role: {name: redhat.satellite.repositories}, tags: ['satellite_repositories']}
