---
- name: send email
  hosts: all
  gather_facts: false
  tasks:
    - name: Sending an e-mail using the remote machine, not the Ansible controller node
      mail:
        host: localhost
        port: 25
        to: Ahmed Eladawy<ahmedfouadeladwy@gmail.com>
        subject: Ansible-report
        body: System  has been successfully provisioned.
