---
- hosts: all
  gather_facts: false
  tasks:
#    - name: set AAP hostname facts
#      set_fact:
#        controller_host: "{{lookup('pipe','hostname')}}"
    - name: get AAP hostname 
      shell: echo $HOSTNAME
      register: controller_host
      delegate_to: localhost

    - name: debug controller_host
      debug:
        var: controller_host
      delegate_to: localhost
