---
- name: mount module demo
  hosts: localhost
  connection: local
  vars:
    uri: "//192.168.122.236/share1"
    username: "sambauser"
    password: "redhat"
    mountpoint: "/share"
  tasks:
    - name: Mount network share
      ansible.posix.mount:
        src: "{{ uri }}"
        path: "{{ mountpoint }}"
        fstype: cifs
        opts: 'username={{ username }},password={{ password }}'
        state: mounted
