---
- name: test systemd mask
  hosts: aeladawy-rhel9-client.example.com
  tasks:
    - name: disable ctrl-alt-delete
      ansible.builtin.systemd:
        name: ctrl-alt-del.target
        masked: true
        enabled: false
#        daemon_reload: true

#    - name: Mask ctrl-alt-delete
#      ansible.builtin.systemd:
#        name: ctrl-alt-del.target
#        masked: true
#        daemon_reload: true
