---
- name: test systemd mask
  hosts: aeladawy-rhel9-client.example.com
  tasks:
    - name: Mask ctrl-alt-delete
      ansible.builtin.systemd:
        name: ctrl-alt-del.target
        enabled: false
        masked: true
        daemon_reload: true
