---
- name: Playbook to test tags
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

    - name: tag1 task
      ansible.builtin.debug:
        msg: "test tag1 task"


    - name: tag2 task
      ansible.builtin.debug:
        msg: "test tag2 task"
