---
- name: cat /etc/krb5.conf file
  gather_facts: false
  hosts: all
  tasks:
    - name: Update status - active = active
      ansible.builtin.blockinfile:
        path: /etc/ansible/facts.d/pf_toolchain.fact
        marker: "# {mark} toolchain status"
        block: "status = false"
        mode: 0644
    - name: show content
      ansible.builtin.command: cat /etc/ansible/facts.d/pf_toolchain.fact
      register: myoutput
    - ansible.builtin.debug:
        msg: "{{ myoutput.stdout }}"
