---
- name: create dir in tower
  gather_facts: false
  hosts: localhost
  connection: local
  tasks:
    - name: test unarchive file
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz
        dest: /runner/

    - name: test wait_for module
      ansible.builtin.wait_for:
        timeout: 60
      delegate_to: localhost
