---
- name: create dir in tower
  gather_facts: false
  hosts: localhost
  connection: local
  tasks:
    - name: create iso directories
      file:
        name: '{{ item }}'
        owner: nobody
        group: nobody
        mode:  "0755"
        state: directory
      loop:
        - /srv/rti/boot-iso
        - /srv/rti/boot-iso/rti-ldapp01
        - /srv/rti/boot-iso-src/rti-ldapp01
      delegate_to: tower
    - command: ls -lZ /srv/rti
      delegate_to: tower
