---
- name: create dir in tower
  gather_facts: false
  hosts: tower
  connection: local
  tasks:
    - name: create iso directories
      file:
        path: /srv/rti/boot-iso
        owner: root
        group: root
        mode:  "0755"
        state: directory
#      loop:
#        - /srv/rti/boot-iso
#        - /srv/rti/boot-iso/rti-ldapp01
#        - /srv/rti/boot-iso-src/rti-ldapp01
      delegate_to: tower
    - name: list dirs
      command: ls -lZ /srv/rti
      delegate_to: tower
