---
- name: Test secret masking in diff output
  hosts: localhost
  gather_facts: false
  vars:
    secret_var: "SuperSecretPassword"
    password: "MyAdminPassword"
    my_secret_var: "AnotherHiddenValue"

  tasks:
    - name: Create test file with secrets
      copy:
        dest: /tmp/test_secrets.txt
        content: |
          secret={{ secret_var }}
          password={{ password }}
          my_secret_var={{ my_secret_var }}
      diff: true

    - name: Modify file to trigger a diff change
      copy:
        dest: /tmp/test_secrets.txt
        content: |
          secret=NEWVALUE
          password=CHANGEDPASS
          my_secret_var=UPDATEDVALUE
      diff: true

    - name: Test explicit debug of secret values
      debug:
        msg: "This contains secret={{ secret_var }} and password={{ password }} and my_secret_var={{ my_secret_var }}"

    - name: Create structured JSON for masking validation
      copy:
        dest: /tmp/structured.json
        content: |
          {
            "secret": "{{ secret_var }}",
            "password": "{{ password }}",
            "nested": {
              "my_secret_var": "{{ my_secret_var }}"
            }
          }
      diff: true
