---
- name: Playbook to test download and copy file
  hosts: tower
  connection: local
  tasks:
  
    - name: "get the stats of the /opt/ansible_files/mbse/test.zip"
      stat:
        path: /tmp/ansible_files/mbse/test.zip
      register: stat_out

    - name: "output the 'stat_out' variable"
      debug:
        msg: "{{ stat_out }}"
        
    - name: Download to local download folder
      get_url:
        url: http://aeladawy-rhel8-tower-client.example.com/test.zip
        dest: /tmp/ansible_files/mbse/test.zip
        force: true
        mode: '0664'



 #   - name: copy file to folder
 #     copy:
 #       src: /opt/ansible_files/mbse/test.zip
 #       dest: /tmp/test.zip
