- name: Playbook to configure ansible tower organizations
  hosts: all
  vars:
    host: https://aeladawy-tower.example.com/
    username: admin
    password: redhat
    verify_ssl: false

  tasks:
    - name: Add webhook notification
      ansible.tower.tower_notification_template:
        name: webhook notification
        organization: test_org
        notification_type: webhook
        notification_configuration:
          url: http://www.example.com/hook
          headers:
            X-Custom-Header: value123
        state: present
