- name: Playbook to configure ansible tower organizations
  hosts: all
#  collections:
#    - redhat_cop.tower_configuration
#    - ansible.tower
#  vars:
#    tower_hostname: https://aeladawy-tower.example.com/
#    tower_username: admin
#    tower_password: redhat
#    verify_ssl: False
    tower_organizations:
#      - name: Satellite
      - name: test_org
  tasks:
    - name: Add webhook notification
      ansible.tower.tower_notification:
        name: webhook notification
        notification_type: webhook
        notification_configuration:
          url: http://www.example.com/hook
          headers:
            X-Custom-Header: value123
        state: present    
