---
- name: Test network_moid from vmware_res
  hosts: localhost
  gather_facts: false

  tasks:
    - name: set connection info
      ansible.builtin.set_fact:
        connection_args:
          vcenter_hostname: mna-emea-lab-vcsa.gsslab.brq2.redhat.com
          vcenter_username: "{{ v_user }}"
          vcenter_password: "{{ v_password }}"
          vcenter_validate_certs: false
  
    - name: Fetch MOIDs
      ansible.builtin.set_fact:
        ansible.builtin.debug: msg="{{ lookup('vmware.vmware_rest.network_moid', 'VM Network', **connection_args) }}"
        validate_certs: no
