---
inventory_all__ansible_temp_dir: "ansible_topics_tmp"
inventory_all__file_mode: "0644"
inventory_all__directory_mode: "0755"
inventory_all__csv_dir: "files/csv"
inventory_all__travic_dir_path: "/opt/travic"
inventory_all__script_dir: "bin"
inventory_all__job_server_command_path: "{{ inventory_all__travic_dir_path }}/run/job-server/tph-job-server.sh"
# see: https://kfw-f-jirap2.kfw.kfwgruppe.net/browse/ZVBBSER-6173
inventory_all__parallel_import_filename: "parallel-topics"
inventory_all__exported_tarball_suffix: "-export.tar.gz"

inventory_all__git_repo_url: "gitlab.apps.ocp-devops-prod.kfw.kfwgruppe.net/kfw/bb-zvr/plattform/tph/config/topics.git"
inventory_all__git_default_branch: "main"
inventory_all__git_local_dir: "topics.git"
inventory_all__git_branch_backup_group: "backup"
inventory_all__git_branch_transfer_group: "transfer"
inventory_all__directory_export: "export"
inventory_all__directory_export_extracted: "export-extracted"
inventory_all__directory_workbench: "workbench"
inventory_all__directory_import: "import"
inventory_all__directory_import_csv: "import/csv"
inventory_all__directory_temp: "tmp"

inventory_all__remove_id_from_csv_exception_list:
  - "UNIT.csv"
  - "BANK_PAIR_CORRESPOND.csv"
  - "CHAN_FORWARD.csv"
  - "CONFIG.csv"
  - "CUST_RATE_SPREAD.csv"
  - "EMBARGO_BIC.csv"
  - "EMBARGO_IBAN.csv"
  - "NAVIGATOR_RULE.csv"
  - "NAV_RULE_DELIVERY_METHOD.csv"
  - "NAV_RULE_EXCLUSIONS.csv"
  - "NAV_RULE_PREFERENCES.csv"
  - "PAYMENT_CAT.csv"
  - "REORG_CONF.csv"
  - "REORG_CONF_FINALIZE.csv"
  - "WFA.csv"
  
inventory_all_csv_files__global_csv_files_path_list:
  - "{{ inventory_all__csv_dir }}/TPHUSER.csv"
  - "{{ inventory_all__csv_dir }}/USERSETTING.csv"

inventory_all__initialization_topic_exceptions_list:
  - "BOOKINGRULES"
  - "NAVBANKS"

inventory_all__initialization_basedata_order:
  - "SST_42_TARGET2-Bestand_FileIn"
  - "SST_43_Bank_Directory_Plus-Bestand_FileIn" # (1. BankDirectoryPlus – 2. Currency -  3. Holiday)
  - "SST_45_IBAN_Structure-Bestand_FileIn"
  - "SST_44_IBAN_Plus-Bestand_FileIn"
  - "SST_46_Marktdaten_FileIn"
  - "SST_47_Korrespondentenkurse_FileIn"
  - "SST_52_Kundenbestand_FileIn"
  - "SST_50_Kontenbestand-FileIn"
  - "SST_51_Zusatz-Kontenbestand-FileIn"
  - "SST_56_RMA-Bestand_FileIn"
  - "SST_49_Bundesbank_SCL-Bestand_FileIn"

# List of topics, which needs to be imported in exactly this order
# see: https://kfw-f-jirap2.kfw.kfwgruppe.net/browse/ZVBBSER-6173
inventory_all__sequential_topics:
  - "MANDANT"
  - "SRV_INTERFACE"
  - "CHANNEL"

inventory_all__environment_role_prefix:
  - environment: "entw1"
    prefix: "ZV-TPH_E"
  - environment: "entw2"
    prefix: "ZV-TPH_E"
  - environment: "entw3"
    prefix: "ZV-TPH_E"
  - environment: "prod1"
    prefix: "ZV-TPH_P"
  - environment: "qsic1"
    prefix: "ZV-TPH_M"
  - environment: "test1"
    prefix: "ZV-TPH_T"
  - environment: "test2"
    prefix: "ZV-TPH_T"
  - environment: "test3"
    prefix: "ZV-TPH_T"

inventory_all__topics:
  - topic: MANDANT
    files:
      - "MAND.csv"
      - "UNIT.csv"
  - topic: SRV_INTERFACE
    files:
      - "SRVIFCFG.csv"
      - "UNIT.csv"
  - topic: CHANNEL
    files:
      - "CHANNEL_IN.csv"
      - "CHANNEL_OUT.csv"
      - "CHAN_FORWARD.csv"
      - "UNIT.csv"
  - topic: BOOKACCOUNTS
    files:
      - "BOOK_ACCOUNT_REL.csv"
      - "UNIT.csv"
  - topic: BOOKINGRULES
    files:
      - "BOOKING_RULE.csv"
      - "UNIT.csv"
  - topic: CONFIGURATION
    files:
      - "CONF.csv"
      - "CONFIG.csv"
      - "UNIT.csv"
  - topic: CORRESPCOND
    files:
      - "CCYCUTOFFTIME.csv"
      - "CORRESP_AGREE.csv"
      - "CORRESP_BIC.csv"
      - "CORRESP_CHARGE.csv"
      - "UNIT.csv"
  - topic: CUSTOMERCOND
    files:
      - "CUSTOMER_AGREEMENT.csv"
      - "CUSTOMER_CHARGE.csv"
      - "CUSTOMER_PRODUCT.csv"
      - "CUSTOMER_VAL_DATE.csv"
      - "CUST_CCY_EXCHANGE.csv"
      - "CUST_COMMON_CHARGE.csv"
      - "UNIT.csv"
  - topic: EMBARGO
    files:
      - "EMBARGOCONFIG.csv"
      - "EMBARGO_BIC.csv"
      - "EMBARGO_IBAN.csv"
      - "UNIT.csv"
  - topic: OUTBULK
    files:
      - "OUT_BULK_CFG.csv"
      - "UNIT.csv"
  - topic: NAVBANKS
    files:
      - "BANK_PAIR.csv"
      - "BANK_PAIR_CCY.csv"
      - "BANK_PAIR_CORRESPOND.csv"
      - "CORRESPOND_ACC.csv"
      - "UNIT.csv"
  - topic: NAVSENDMODE
    files:
      - "NAVIGATOR_DC_CONFIG.csv"
      - "UNIT.csv"
  - topic: NAVRULES
    files:
      - "NAVIGATOR_RULE.csv"
      - "NAV_RULE_DELIVERY_METHOD.csv"
      - "NAV_RULE_EXCLUSIONS.csv"
      - "NAV_RULE_PREFERENCES.csv"
      - "PAYMENT_CAT.csv"
      - "UNIT.csv"
  - topic: REORG
    files:
      - "REORG_CONF.csv"
      - "REORG_CONF_FINALIZE.csv"
      - "UNIT.csv"
  - topic: ROLESANDUSERS
    files:
      - "ROLE.csv"
      - "TPHUSER.csv" # Must be empty file
      - "UNIT.csv"
      - "USERSETTING.csv" # Must be empty file
  - topic: TASK_CONFIGURATION
    files:
      - "TASK_CONF.csv"
      - "UNIT.csv"
  - topic: WORKFLOWS
    files:
      - "UNIT.csv"
      - "WFA.csv"

# See: https://kfw-f-jirap2.kfw.kfwgruppe.net/browse/ZVBBSER-6090
inventory_all__specific_topics_tph_5_3:
  - topic: CUSTOMERCOND
    files:
      - "CUSTOMER_AGREEMENT.csv"
      - "CUSTOMER_CHARGE.csv"
      - "CUSTOMER_PRODUCT.csv"
      - "CUSTOMER_VAL_DATE.csv"
      - "CUST_CCY_EXCHANGE.csv"
      - "CUST_RATE_SPREAD.csv"
      - "CUST_COMMON_CHARGE.csv"
      - "UNIT.csv"

inventory_all__specific_topics_tph_5_4: "{{ inventory_all__specific_topics_tph_5_3 }}"
