- name: Hello World Sample
  hosts: all
  gather_facts: yes
  environment:
#    ANSIBLE_CALLBACK_PLUGINS:
#      - "/runner/project/playbooks_with_callback/callback_plugins/"
    ANSIBLE_CALLBACKS_ENABLED:
      - profile_tasks_new
      - timer_new
  
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ hello_message }}"
